### ISSUE TITLE
FluidTank NBT bug with Forge 1291+

### ISSUE THREAD

**Issue by mallrat208** [RedGear/Brewcraft#18]
Sorry, can't think of a more descriptive title for this...

Brewcraft 1.2.3
RedGearCore 2.2.1
Forge 1231, 1286, and 1291 Tested

This only affects for 1291 and beyond. There was a change made to how tanks handle checking for the empty nbt tag. 

https://github.com/MinecraftForge/MinecraftForge/commit/e629774753bc74f7565a01080f8bad774941ebaf

Found this out by putting a Keg next to a Railcraft Water Tank. The Water Tank was ejecting Fluid though the Keg wasn't building any up inside it. After reverting to 1286, the water showed up in the keg properly.

**Comment by mallrat208** [comment]
As an update: The tanks are properly storing the fluid. The gui just shows them as empty.

**Comment by kutschkem** [comment]
What needs to be done to fix this? I suppose this is actually a problem in RedGearCore, since the tank code in here seems rather smallish. I don't know enough about Forge or even Minecraft mods to make a fix, but would be willing to try if someone helps me to find where to look.

**Comment by DillonJettCallis** [comment]
Almost certainly the change needs to be made to Core. I've retired from modding, and don't have the time to do it. If you want to take a shot at it, feel free to do so.
